name=BURT temperature sensor
version=1.0.0
author=Levi Lesches <levilesches@gmail.com>
maintainer=Levi Lesches <levilesches@gmail.com>
sentence=Reads the temperature sensor
paragraph=Checks to see if the device is overheating
category=Device Control
url=https://github.com/BinghamtonRover/control-firmware
